apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-unshorten
  labels:
    app: unshorten-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unshorten-api
  template: 
    metadata:
      labels:
        app: unshorten-api
    spec:
      containers:
      - name: unshorten-api-container
        image: "127.0.0.1:30400/link-unshorten:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
 name: link-unshorten-service
spec:
 type: NodePort
 ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
 selector:
   app: unshorten-api