apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-unshorten
  labels:
    app: unshorten-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unshorten-api
  template: 
    metadata:
      labels:
        app: unshorten-api
    spec:
      containers:
      - name: unshorten-api-container
        image: "127.0.0.1:30400/link-unshorten:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP